### ISSUE TITLE
Review the API

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStore-Client-Go#10]
Need to review the exposed API and the implementation of proto.
Ensure that the API is idiomatic golang

**Comment by alexrudd** [comment]
Hey, looks like there's some ongoing discussion about client API. I'm only just getting to grips with EventStoreDB but I have a fair amount of experience with Go.

Going off of the underlying [gRPC service interface](https://github.com/EventStore/EventStore/blob/789ab7c8f848454841ac4f9bddcb550244186b1a/src/Protos/Grpc/streams.proto#L7), I think the client API could be simplified considerably for Reads.

gRPC Interface:

```go
type StreamsClient interface {
	Read(ctx context.Context, in *ReadReq, opts ...grpc.CallOption) (Streams_ReadClient, error)
	Append(ctx context.Context, opts ...grpc.CallOption) (Streams_AppendClient, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error)
	Tombstone(ctx context.Context, in *TombstoneReq, opts ...grpc.CallOption) (*TombstoneResp, error)
}
```

Proposed client API for Read and Subscribe behaviours using variadic `ReadOption` parameter:

```go
import api "github.com/EventStore/EventStore-Client-Go/protos/streams"

// Client for calling the EventStoreDB gRPC API.
type Client struct {...}

// Read and return all events currently in the DB
func (c *Client) Read(ctx context.Context, opts ...ReadOption) ([]messages.RecordedEvent, error) {
    readReq, err := applyReadOptions(newDefaultReadReq(), opts...)
    if err != nil {
        return nil, fmt.Errorf("applying read request options: %w", err)
    }

    var events []messages.RecordedEvent
    stream, err := c.stream.Read(ctx, readReq)
    // TODO: perform read until io.EOF

    return events, nil
}

// Read and return all events currently in the DB
func (c *Client) Subscribe(ctx context.Context, handler func(messages.RecordedEvent), opts ...ReadOption) error {
    readReq, err := applyReadOptions(newDefaultReadReq(), opts...)
    if err != nil {
        return fmt.Errorf("applying read request options: %w", err)
    }

    stream, err := c.stream.Read(ctx, readReq)
    // TODO: read from stream and forward events onto the handler

    return nil
}

// ReadOptions are applied to ReadReqs before calling the underlying gRPC API.
type ReadOption func(*api.ReadReq) error

// Example ReadOptions for commonly configured behaviours, or implment your own.
func WithDirection(direction direction.Direction) ReadOption {...}
func WithFromPosition(from position.Position) ReadOption {...}
func WithLimit(count uint64) ReadOption {...}
func WithLinksResolved() ReadOption {...}
func WithStreamID(streamID string) ReadOption {...}
func WithStreamPrefixes(prefixes []string) ReadOption {...}
func WithEventTypes(types []string) ReadOption {...}
func WithCheckpointHandler(handler func(position.Position)) ReadOption {...}
func WithSubDroppedHandler(handler func(reason string)) ReadOption {...}
func WithFilter(filter filtering.SubscriptionFilterOptions) ReadOption {...}

// newDefaultReadReq return a ReadReq with most common settings pre-configured
func newDefaultReadReq() *api.ReadReq {...}

// applyReadOptions applies ReadOptions to an existing ReadReq.
func applyReadOptions(req *api.ReadReq, opts ...ReadOption) (*api.ReadReq, error) {
    for _, applyOpt := range opts {
        if err := applyOpt(req); err != nil {
            return fmt.Errorf("applying read option: %w", err)
        }
    }

    return nil
}
```

The focus of the above API is to reduce the number parameters for each method to just those that are actually required, while allowing for a variadic number of `ReadOption`s to be applied optionally. This makes the API much for accessible (without having to understand the complete depth of available features), but still exposes all available features for power users. It also makes the documentation easier to write (explanations of features are localised around the ReadOptions), and easier to consume.

The functional options as parameters is a common pattern emerging in a lot of Go libraries atm. It makes extending API functionality easy and even allows consumers to define their own custom options without being blocked by library maintainers.

You'd probably also want to define to additional utility methods for very common access behaviours, such as: `ReadStreamEvents(..)`, `ReadAllOfEventType(...)` `SubscribeToStream(...)`, etc. Also exposing `api.ReadReq` as part of the client is not ideal, so you'd probably want to define your own public `ReadReq` type that is then coverted to a `api.ReadReq`.

**Comment by alexeyzimarev** [comment]
I think it makes total sense, however, we need to be careful about putting together unrelated options. Maybe, we need more specific options.

For example:

```
func WithDirection(direction direction.Direction) ReadOption {...}
```
is always needed, with `Forward` as default

```
func WithFromPosition(from position.Position) ReadOption {...}
```
is mandatory, so it's not an _option_

```
func WithLimit(count uint64) ReadOption {...}
```
is not mandatory

```
func WithLinksResolved() ReadOption {...}
```
is always needed, default is `true`

```
func WithStreamID(streamID string) ReadOption {...}
```
is mandatory, you have to read from something, so it's not an _option_

```
func WithStreamPrefixes(prefixes []string) ReadOption {...}
func WithEventTypes(types []string) ReadOption {...}
func WithCheckpointHandler(handler func(position.Position)) ReadOption {...}
func WithSubDroppedHandler(handler func(reason string)) ReadOption {...}
func WithFilter(filter filtering.SubscriptionFilterOptions) ReadOption {...}
```
are only for server-side filtering

I can suggest `WithFilter`, which then would allow specifying filter-specific options.

Mandatory parameters should probably not be options at all.

**Comment by alexrudd** [comment]
I guess I was classifying parameters that have a clear defaults as also being optional. I don't know if you have access to usage data, but say if 99% of Read requests are made with the direction set for "forward", does it make sense that 100% of Read calls on the client must include a read direction?

Specifically in the case of read direction, maybe the option that would make more sense would be:

```go
func WithBackwardsDirection() ReadOption {...}
```

That would make it clear that the default direction is forward, but you have the option to read backwards.
