### ISSUE TITLE
Problem importing v2 of the client

### ISSUE THREAD

**Issue by marcinbudny** [EventStore/EventStore-Client-Go#111]
Hi, 

I'm not able to import the recently published version 2 of the ESDB Go client. I've been using v1 with no major issues so far.

When trying to import v2, I get following error:
```
$ go get github.com/EventStore/EventStore-Client-Go@v2.0.0
go: github.com/EventStore/EventStore-Client-Go@v2.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/EventStore/EventStore-Client-Go/v2")

$ go get github.com/EventStore/EventStore-Client-Go/v2@v2.0.0
go: github.com/EventStore/EventStore-Client-Go@v2.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/EventStore/EventStore-Client-Go/v2")
```

According to [this blog post](https://go.dev/blog/v2-go-modules), a major version change of a go module needs to be reflected in the module path. Looking at `go.mod` of the ESDB client, it seems that in fact `/v2` is not present. Am I missing something?

**Comment by YoEight** [comment]
Hey @marcinbudny,

Thanks for reporting that issue.

#112 should sold that issue.

**Comment by YoEight** [comment]
@marcinbudny release `v2.0.1` is available

**Comment by marcinbudny** [comment]
I was able to import this version, thanks.
