### ISSUE TITLE
Possible memory leak on client close

### ISSUE THREAD

**Issue by marcinbudny** [EventStore/EventStore-Client-Go#113]
Hi, 

I noticed that multiple client create-close cycles  continuously increase memory usage of my application. Here's a minimal repro:

```go
package main

import (
	"time"

	esdb "github.com/EventStore/EventStore-Client-Go/v2/esdb"
)

var esConfig *esdb.Configuration = &esdb.Configuration{
	Address:                     "localhost:2113",
	DisableTLS:                  true,
	SkipCertificateVerification: false,
	DiscoveryInterval:           100,
	GossipTimeout:               5,
	MaxDiscoverAttempts:         10,
	KeepAliveInterval:           10 * time.Second,
	KeepAliveTimeout:            10 * time.Second,
}

func main() {
	for {
		openClose()
	}
}

func openClose() {
	client, err := esdb.NewClient(esConfig)
	if err != nil {
		panic(err)
	}
	defer client.Close()

	time.Sleep(5 * time.Millisecond)
}
```

When this program runs, I observe following memory consumption pattern:

![image](https://user-images.githubusercontent.com/2671162/160250683-68f70c32-7758-43b6-984b-9361eb27b92f.png)

My suspicion is that the `connectionStateMachine` goroutine does not return on client close, so essentially the application leaks goroutines.

**Comment by YoEight** [comment]
Thanks for submitting this issue @marcinbudny 

PR #114 addresses it.

**Comment by YoEight** [comment]
v2.0.2 has been released and contains the memory leak patch among other things.
