### ISSUE TITLE
Cleanup eventstoredb in each test

### ISSUE THREAD

**Issue by mehdihadeli** [EventStore/EventStore-Client-Go#142]
Hi,
Firstly, thanks for your useful library.
How can I clean up `eventstoredb` in each integration test?

**Comment by YoEight** [comment]
Hey @mehdihadeli, I would advise you to run the database in in-memory mode in that case. You can achieve that by setting the env variable `EVENTSTORE_IN_MEM` to `true` or `1` when running the container.

**Comment by mehdihadeli** [comment]
Hi,
Thanks, Let me check.
