### ISSUE TITLE
Support ReadAllStreams for getting all streams

### ISSUE THREAD

**Issue by mehdihadeli** [EventStore/EventStore-Client-Go#143]
Hi,
I think currently there is no functionality for getting all streams, Is it possible to add it?

**Comment by YoEight** [comment]
The database doesn't have a first class feature that returns you all streams. However there is a way to get around this by using projections, in this case the `$streams` projection: https://developers.eventstore.com/server/v22.10/projections.html#streams-projection

Please consider that projections aren't a free lunch so have a look on potential performance impact there: https://developers.eventstore.com/server/v22.10/projections.html#performance-impact

**Comment by mehdihadeli** [comment]
Thanks,
I just wanted to get all streams and delete them one by one in my tests.
