### ISSUE TITLE
How to determine if stream is non-existing on subscription

### ISSUE THREAD

**Issue by wiegell** [EventStore/EventStore-Client-Go#147]
The documentation explains how to check if a stream exists when doing a read:
https://developers.eventstore.com/clients/grpc/reading-events.html#checking-if-the-stream-exists

But the subscription.Recv() does not return an error - what happens if i try and subscribe to a non-existing stream? And how to handle it? Do i need to first check if the stream exists with a read?

**Comment by YoEight** [comment]
Hey @wiegell, subscribing to a non existing stream is not an error. Eventually, you'd receive something if an event is appended to that stream at some point.

**Comment by wiegell** [comment]
Ok thanks for the clarification
