### ISSUE TITLE
Ensure multiple subscriptions can be handled

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStore-Client-Go#15]
Ensure that multiple subscriptions to the same and different streams are handled independently of each other. e.g. Getting events, stopping the subscription

**Comment by pvanbuijtene** [comment]
There's a catch on reading and writing to the same stream, as mentioned [here](https://grpc.io/docs/languages/go/generated-code/):

_Thread-safety: note that client-side RPC invocations and server-side RPC handlers are thread-safe and are meant to be run on concurrent goroutines. But also note that for individual streams, incoming and outgoing data is bi-directional but serial; so e.g. individual streams do not support concurrent reads or concurrent writes (but reads are safely concurrent with writes)._

**Comment by YoEight** [comment]
Fixed by #56
