### ISSUE TITLE
There is a slight difference between official document and source code.

### ISSUE THREAD

**Issue by kunkka19xx** [EventStore/EventStore-Client-Go#194]
Hi ESDB team, 
Thank you for the great works and detailed documents. 
I am following the documentation to implement my service with esdb but I found that there is a slight difference between official document and source code.
Ref:
https://developers.eventstore.com/clients/grpc/appending-events.html#append-your-first-event

**In the last example:** 

1. I can not find the OriginalStreamRevision() method

```go
aopts := esdb.AppendToStreamOptions{
    ExpectedRevision: lastEvent.OriginalStreamRevision(),
}
```

I got the error told me that: 

_lastEvent.OriginalStreamRevision undefined (type *esdb.ResolvedEvent has no field or method OriginalStreamRevision)_

![image](https://github.com/user-attachments/assets/2331e400-b54d-4a9c-9b6b-9a63ddddd54c)

- Now I don't know how to use/ find the StreamRevision of the lastEvent even checked the package source. 

2. And another tiny one is Json Type constant: 

_undefined: esdb.ContentTypeJson_
But with this one I can easily find the alternative (esdb.JsonContentType)

- I hope I can get the solution for the first one. 
- Or if my referred documentation was wrong or out of date, could you please provide me a right one. 
Thank you so much

**Comment by w1am** [comment]
Hey @kunkka19xx,

The `OriginalStreamRevision` method is provided by the `ResolvedEvent` struct in the `esdb` package, so it should be available in your code. Can you verify that you imported the `github.com/EventStore/EventStore-Client-Go/v4/esdb` package?

For reference, you can also check the source code that we use in the code snippets:

https://github.com/EventStore/EventStore-Client-Go/blob/c29aa7d3ce9c0aadc7d2bfa3dd060f2865efb227/samples/appendingEvents.go#L154

**Comment by kunkka19xx** [comment]
@w1am  
Thank you for your reply. 
My import was: 

```go
"github.com/EventStore/EventStore-Client-Go/esdb"
```

after I changed it to v4, it worked !!!
