### ISSUE TITLE
Setting position for AppendToStream

### ISSUE THREAD

**Issue by bweston92** [EventStore/EventStore-Client-Go#21]
I need a way of setting the expected position for the events to go in at on the stream.

The func signature of what I am calling from this package:
```
func (client *Client) AppendToStream(context context.Context, streamID string, streamRevision stream_revision.StreamRevision, events []messages.ProposedEvent) (*WriteResult, error) {
```

I assumed `stream_revision.StreamRevision` and tried it like so:
```
// ...
sr := streamrevision.StreamRevisionNoStream
if expectedPosition > 0 {
	sr = streamrevision.NewStreamRevision(expectedPosition)
}
// ...
_, err := c.AppendToStream(ctx, streamPrefix + "-" + aggregateID.String(), sr, ce)
// ...
```

However this doesn't work. Any ideas?

Any help is appreciated.

**Comment by bweston92** [comment]
@pgermishuys any ideas?

**Comment by YoEight** [comment]
@bweston92 Sorry for some reason that issue didn't show up in my notifications.

Could you be more specific when you say it doesn't work? Also, when you are saying "expected position", did you mean expected revision of a stream or did you actually mean expected position in the transaction log?

**Comment by bweston92** [comment]
@YoEight basically,

If I have an empty stream and I set the stream revision to be `streamrevision.StreamRevisionNoStream` is works fine, if the stream exists it errors.

If I have read from a stream and want to append more events from the position I have read up until (which I believed to be the end of the stream when I do my transaction) I want to guarantee there is no concurrency issue by only appending to the stream at the position, I attempt this by setting the stream revision to `streamrevision.NewStreamRevision(expectedPosition)` where expectedPosition is number of events + 1. However the following it append new events at the end of the stream regardless if there is now new events at that position in the stream.

**Comment by bweston92** [comment]
```
[completed] adding 4 events at position 0 in stream foo-693628ce-ab95-4056-b086-37ff0130afe3
[completed] adding 2 events at position 1 in stream foo-693628ce-ab95-4056-b086-37ff0130afe3
```

The above I would expect to fail as it added 4 events at stream revision 0 (new stream) then tried to add 2 events but from stream revision 1, but this completed without error and actually put them in at the end so when I read the stream it has 5 events.

**Comment by YoEight** [comment]
I think your issue is because you added an extra `1` at your expected position:

>  where expectedPosition is number of events + 1

Position (or rather revision because there is also position in EventStoreDB) are indexes. What you did is a off-by-one error. Could you remove the `+1` and tell me how it went?

**Comment by bweston92** [comment]
The logs in my second response show me adding 4 events to a stream and then adding 2 more events from the revision 1, which is lower then 3 or 4.

**Comment by bweston92** [comment]
Ok however it does work if I add 7 events first and then append from revision 4.

So after looking further is looks like the library reserves the first 3 stream revisions using the itoa.

https://github.com/EventStore/EventStore-Client-Go/blob/bea705ec8b63f75dcd0a4ce4bd2f61f0ebe6ef00/streamrevision/streamrevision.go#L6

https://github.com/EventStore/EventStore-Client-Go/blob/bea705ec8b63f75dcd0a4ce4bd2f61f0ebe6ef00/internal/protoutils/protobuf_utils.go#L31
