### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by iangregsondev** [EventStore/EventStore-Client-Go#31]
Am I missing something?

I can't find any docs or any info

**Comment by alexeyzimarev** [comment]
Yhe client library hasn't reached the GA phase yet. The initial basic documentation is available in the readme file. We will add this client to the docs as aoon as the API gets stable.

**Comment by iangregsondev** [comment]
Ah Ok @alexeyzimarev , sorry, I didn't realise, i thought it was a bit weird as I couldn't figure out what to do..

I will keep my eye on it then - thanks
