### ISSUE TITLE
Catch-up subscription skiping the first event

### ISSUE THREAD

**Issue by FabioBentoLuiz** [EventStore/EventStore-Client-Go#33]
**Describe the bug**
Executing SubscribeToStream (from = streamrevision.StreamRevisionStart) skips the first event from the stream.

**Expected behavior**
Get all the events from the stream (event number 0 inclusive) and keep listening for new ones.

**EventStore details**
"ES VERSION:"     "20.6.1.0" ("tags/oss-v20.6.1"/"9ea108855", "Unknown")
"OS:"                     Linux ("Unix 5.4.39.0")
"RUNTIME:"          ".NET 3.1.9" (64-bit)
"GC:"                     "3 GENERATIONS"

**EventStore Installation**
docker run --rm --name eventstore -p 2113:2113 -p 1113:1113 \
 eventstore/eventstore:latest --insecure --log-level=Verbose --run-projections=All

**Logs**
[    1,38,15:42:26.958,INF] Catch-up subscription 9fcd73f2-fc08-41f8-8ee9-30ccb33b174d to "order-stream"@"1" running...
[    1,38,15:42:26.959,VRB] Catch-up subscription 9fcd73f2-fc08-41f8-8ee9-30ccb33b174d to "order-stream" reading next page starting from "1".
[    1,35,15:42:26.961,VRB] Catch-up subscription 9fcd73f2-fc08-41f8-8ee9-30ccb33b174d to "order-stream" received event "1".
[    1,35,15:42:26.962,VRB] Catch-up subscription 9fcd73f2-fc08-41f8-8ee9-30ccb33b174d to "order-stream" reading next page starting from "2".
[    1,35,15:42:26.963,VRB] Subscription 9fcd73f2-fc08-41f8-8ee9-30ccb33b174d to "order-stream" reached the end at "1", switching...
[    1,35,15:42:26.963,INF] Live subscription 9fcd73f2-fc08-41f8-8ee9-30ccb33b174d to "order-stream" running from "1"...
[    1,35,15:42:26.964,VRB] Live subscription 9fcd73f2-fc08-41f8-8ee9-30ccb33b174d to "order-stream" confirmed at "2".
[    1,35,15:42:26.964,VRB] Live subscription 9fcd73f2-fc08-41f8-8ee9-30ccb33b174d to "order-stream" loading any missed events starting from "1"
[    1,38,15:42:26.968,VRB] Live subscription 9fcd73f2-fc08-41f8-8ee9-30ccb33b174d to "order-stream" caught up at "1".

**Relevant code**
```go
subscription, err := client.SubscribeToStream(
		context.Background(),
		"order-stream",
		streamrevision.StreamRevisionStart,
		false,
		func(e messages.RecordedEvent) {
			log.Printf("New event: %v", e)
		},
		nil,
		func(reason string) {
			log.Printf("EventStoreDB subscription dropped. Reason: %s", reason)
			//TODO: handle re-subscription
		})
```

**From Admin UI / Debug**
```javascript
fromStream('order-stream')
.when({
$any: function(s,e){
log(JSON.stringify(e));
}
})
```
output:

```json
{
    "correlationId": "1dbdfa1c-314a-48ad-b053-41564abb0659",
    "readerPosition": {
        "$s": {
            "order-stream": 1
        }
    },
    "events": [
        {
            "eventStreamId": "order-stream",
            "eventType": "order-released",
            "data": {
                "id": "5fad54bb43c256000184f494",
                "target_qty_bags": 0,
                "product": "opc"
            },
            "isJson": true,
            "readerPosition": {
                "$s": {
                    "order-stream": 0
                }
            }
        },
        {
            "eventStreamId": "order-stream",
            "eventNumber": 1,
            "eventType": "order-released",
            "data": {
                "id": "5fad54ef43c256000184f495",
                "target_qty_bags": 0,
                "product": "opc"
            },
            "isJson": true,
            "readerPosition": {
                "$s": {
                    "order-stream": 1
                }
            }
        }
    ]
}
```

**Comment by bweston92** [comment]
Just come across this now. Any idea how to fix @thefringeninja @YoEight @hayley-jean ?

**Comment by thefringeninja** [comment]
This is by design, as subscribing is an _exclusive_ operation. Please use the overload that does not take a `StreamPosition` argument.

https://developers.eventstore.com/clients/dotnet/generated/v20.6.1/subscribing-to-streams/#subscribing-to-a-stream

**Comment by FabioBentoLuiz** [comment]
Hi @thefringeninja, thank you for the help.

I see that you suggested a link to the .net client, but I could not find an equivalent overload for this golang client. 

Using `client.ReadStreamEvents` I can read all the events (inclusive the event 0), but with a catch-up subscription it would make things a lot easier in my scenario.

I understand that this go client [hasn't reached the GA phase yet](https://github.com/EventStore/EventStore-Client-Go/issues/31), so maybe there are still pending implementations. Anyway, I appreciate any other suggestions and recommendations.

**Comment by bweston92** [comment]
@FabioBentoLuiz so your solution is too use `ReadStreamEvents` for the first event then use `SubscribeToStream` afterwards?

**Comment by bweston92** [comment]
I can see that doing the following works, I'm intrigued as to why this shouldn't be default behaviour. Would be nice if we had #10 so we can do `client.SubscribeToStream` with options such as `FromRevision(uint64)` and `FromStart` as we don't have overloading.

```

func toReadStreamOptionsFromStreamAndStreamRevision(streamID string, streamRevision uint64) *api.ReadReq_Options_Stream {
	if streamRevision == 0 {
		return &api.ReadReq_Options_Stream{
			Stream: &api.ReadReq_Options_StreamOptions{
				StreamIdentifier: &shared.StreamIdentifier{
					StreamName: []byte(streamID),
				},
				RevisionOption: &api.ReadReq_Options_StreamOptions_Start{
					Start: &shared.Empty{},
				},
			},
		}
	}

	return &api.ReadReq_Options_Stream{
		Stream: &api.ReadReq_Options_StreamOptions{
			StreamIdentifier: &shared.StreamIdentifier{
				StreamName: []byte(streamID),
			},
			RevisionOption: &api.ReadReq_Options_StreamOptions_Revision{
				Revision: uint64(streamRevision),
			},
		},
	}
}
```

**Comment by FabioBentoLuiz** [comment]
Hi @bweston92,
yes, for now I'm reading the event 0 with `ReadStreamEvents` like this:

```go
events, err := client.ReadStreamEvents(context.Background(), direction.Forwards, "order-stream", streamrevision.StreamRevisionStart, 1, false)
// process events[0]
```

then subscribing to the stream

```go
subscription, err := client.SubscribeToStream(
		context.Background(),
		"order-stream",
		streamrevision.StreamRevisionStart,
		false,
		func(e messages.RecordedEvent) {
			log.Printf("New event: %v", e)
		},
		nil,
		func(reason string) {
			log.Printf("EventStoreDB subscription dropped. Reason: %s", reason)
			//TODO: handle re-subscription
		})
```

My goal is to replay all the events in a stream. Do you have any better way to do it with the go client?

**Comment by bweston92** [comment]
@FabioBentoLuiz I started to go down that route, however I have generated the persistent subscriptions client and passed connection from client member Conn.

Proto here: https://github.com/EventStore/EventStore/blob/master/src/Protos/Grpc/persistent.proto

Also saved me from needing to store the current position somewhere.

**Comment by YoEight** [comment]
Fixed
