### ISSUE TITLE
Typo in ErrWrongExpectedStreamRevision error message

### ISSUE THREAD

**Issue by mdelez** [EventStore/EventStore-Client-Go#46]
Should be "WrongExpectedStreamRevision" instead of "WrongExceptedStreamRevision"

`var ErrWrongExpectedStreamRevision = errors.New("WrongExceptedStreamRevision")`

I can open a PR if you'd like

**Comment by hayley-jean** [comment]
Thanks for opening this @mdelez! It's been fixed with https://github.com/EventStore/EventStore-Client-Go/pull/47
