### ISSUE TITLE
Update to support EventStore version 21.6.0 or greater

### ISSUE THREAD

**Issue by pivonroll** [EventStore/EventStore-Client-Go#53]
Current supported version is 20.6.0-buster-slim which is last year release and it has a set of few bugs, most notably in persistent subscriptions which are resolved in 21.6.0.
What needs to be done
1. Check if streams proto is updated and generate new golang code and update stream implementation.
2. I would suggest that we ditch the grpc Test Data Client and rewrite tests for streams so that they include data setup phase (writing events). That way it would be easier for developers to read tests and understand the behavior of features.

Persistent subscriptions are already up to date with EventStore 21.6.0.

**Comment by pivonroll** [comment]
@hayley-jean
Hi, is there a repository where I could find test data used to fill the database for gRPC Test Data Docker Image?

**Comment by radovanEmbroker** [comment]
Regarding points 2. and 3. I would suggest that we ditch the grpc Test Data Client and rewrite tests for streams so that they include data setup phase (writing events).
That way it would be easier for developers to read tests and understand the behavior of features.

**Comment by YoEight** [comment]
Not in favor of your 2nd point as the testdata set is about testing invariants. If you push your events yourself, it's possible to be blind to some implementation errors. I think writing your own data to the database should be done alongside the testdata tests.

**Comment by pivonroll** [comment]
If I understand you correctly, we need to have pre-filled database (done by some other client or some other method) in order to be able to test other client (Golang client in this case) so that we can guarantee that client which is tested implements invariants properly?

If so, could we maybe provide a more transparent process on how database for gRPC test data docker image is filled. For example, provide JSON files for events and streams which are written to the gRPC test data docker image. That way each developer can use desired EventStore version through docker image to create it's own EventStore docker container, prefilled it's database and extract that database from that container and use it whenever they need to use desired version of EventStore with pre-filled database in their tests.
This would require to maintain those JSON files to accommodate for invariant type updates in EventStore. But still we would not need to wait for someone to release a new version of gRPC test data docker image. We could built it ourselves locally for our own needs.
