### ISSUE TITLE
Persistent Subscription Read error

### ISSUE THREAD

**Issue by RishiRavikumar** [EventStore/EventStore-Client-Go#59]
func (persistent.SyncReadConnection).Read() seems to be giving a null pointer exception on reading deleted events on the $by_category stream

[https://discuss.eventstore.com/t/persistent-subscription-read-error/3423](url)

**Comment by YoEight** [comment]
Hi @RishiRavikumar, thanks for reporting this. that issue is addressed by #58

**Comment by hayley-jean** [comment]
Fixed by https://github.com/EventStore/EventStore-Client-Go/issues/58
