### ISSUE TITLE
No Connect() function on client.Client, How to connect?

### ISSUE THREAD

**Issue by nolanrsherman** [EventStore/EventStore-Client-Go#62]
This API has changed since the last time I used it. But I noticed there is no longer a Connect() function and I am getting a "Connection Closed" error when trying to use.  Could you provide an example on how to connect? I'd be happy to contribute to the README file here with an example once I get it working.

Steps:
1. Run docker image `eventstore/eventstore:20.6.0-buster-slim` in dev mode.
2. Install the go sdk `github.com/EventStore/EventStore-Client-Go v0.0.0-20210901083018-267dadb3ad6f `
3. Connect with: 
```
	log.Println("starting app")
	config, err := eventClient.ParseConnectionString(connString)
	if err != nil {
		log.Fatalf("could not create client configuration: %s", err.Error())
	}
	log.Printf("Config = %v", config)

	client, err := eventClient.NewClient(config)
	if err != nil {
		log.Fatalf("could not create client: %s", err.Error())
	}
	// client.Connect() ???
	// err = client.CreatePersistentSubscription(context.Background(), persistent.SubscriptionStreamConfig{})
	// if err != nil {
	// 	log.Fatalf("could not connect to client: %s", err.Error())
	// }
	defer client.Close()
```

4. Make an appendToStreamCall
5. Error returned "Could not construct append operation. Reason: rpc error: code = Unavailable desc = connection closed"
	
	
Thanks,
Nolan

**Comment by nolanrsherman** [comment]
I was using the incorrect docker container. 

` eventstore/eventstore:21.6.0-buster-slim` is what this sdk is being tested against.

I get another error when running the append function, but I'll open a new ticket.

**Comment by YoEight** [comment]
Hi there.

The Go client test suite is running "20.6" version of the server no problem. The version is not the issue here. About your initial question, there is no `Connect` function. The 'real' connection is done internally and automatically.

**Comment by nolanrsherman** [comment]
Hi there. Thank you for your response. After reviewing the source code, I came to that realization and I appreciate you taking the time respond and confirm that. My second issue was of my own doing again, my slice of events had an empty element because I misused the make() function syntax. When I corrected my payload, things worked as normal.

Thank you again,
Nolan
