### ISSUE TITLE
No method to connect to PersistentSubscriptionAll

### ISSUE THREAD

**Issue by gionapaolini** [EventStore/EventStore-Client-Go#82]
Hi,

I can successfully create a persistent subscription that listens to specific events by doing: 
```
db.CreatePersistentSubscriptionAll(
	context.Background(),
	"GroupName",
	esdb.PersistentAllSubscriptionOptions{
		Filter: &esdb.SubscriptionFilter{
			Type:     esdb.EventFilterType,
			Prefixes: []string{"EventType-"},
		},
	},
)
```
But I could not find the method to subscribe to it without passing a stream name:
```
db.ConnectToPersistentSubscription(
   context.Background(),
   ???, 
   "GroupName", 
   esdb.ConnectToPersistentSubscriptionOptions{}
)
```
Am I missing something or it's just not implemented yet?

**Comment by YoEight** [comment]
Hi @gionapaolini and thanks for reporting this.

You are right and it seems there was an oversight in this regard. I'll get a PR ready today.

**Comment by gionapaolini** [comment]
Great, thanks for the swift fix!

**Comment by YoEight** [comment]
@gionapaolini The new v1.0.2 release exposed that function back.
