### ISSUE TITLE
 Standardize Go gRPC client deadlines

### ISSUE THREAD

**Issue by tambeau** [EventStore/EventStore-Client-Go#92]
Standardize deadlines across clients

- [ ] Use `defaultDeadline` as a global setting and `deadline` as an operation-level setting
- [ ] Return a `DeadlineExceeded` error on timeout
- [ ] Set stream/$all reads & stream/$all subscriptions timeouts to infinity by default
- [ ] Set timeouts for operations that are not stream/$all reads or subscriptions to 10 seconds by default
- [ ] Allow specifying deadlines on each operation apart from stream/$all subscription operations
- [ ] `defaultDeadline` only applies to operations that don't have a default timeout of infinity
- [ ] Batch Append deadline is 10 seconds

**Comment by ylorph** [comment]
to check if done in  #108

**Comment by YoEight** [comment]
Done in #108
