### ISSUE TITLE
Add missing samples for persistent subscription management API

### ISSUE THREAD

**Issue by oskardudycz** [EventStore/EventStore-Client-Go#94]
Not all methods included in https://github.com/EventStore/EventStore-Client-Go/pull/87 have samples, see:
- https://developers.eventstore.com/clients/grpc/persistent-subscriptions.html
- https://github.com/EventStore/EventStore-Client-Dotnet/blob/master/samples/persistent-subscriptions/Program.cs

**Comment by ylorph** [comment]
@ylorph please check
