### ISSUE TITLE
Vague error message when attempting to create persistent subscription to $all

### ISSUE THREAD

**Issue by lukeparkzip** [EventStore/EventStore-Client-Go#95]
Hi there,

I'm attempting to create a persistent subscription to `$all` using the following code (where `s.client` is an `*esdb.Client`):

```go
func (s *Subscription) Run(ctx context.Context) error {
	return s.client.CreatePersistentSubscriptionAll(ctx, "MyGroupName", s.getCreationOptions())
}

func (s *Subscription) getCreationOptions() esdb.PersistentAllSubscriptionOptions {
	return esdb.PersistentAllSubscriptionOptions{
		From: esdb.Start{},
		Settings: &esdb.SubscriptionSettings{
			ResolveLinkTos:        true,
			MaxRetryCount:         10,
			MinCheckpointCount:    10,
			MaxCheckpointCount:    500,
			MaxSubscriberCount:    10,
			NamedConsumerStrategy: esdb.ConsumerStrategy_Pinned,
			MessageTimeoutInMs:    10000,
			CheckpointAfterInMs:   1000,
		},
	}
}
```

Which is producing the following error:

```text
2022/02/01 12:58:40 [error] unexpected exception: rpc error: code = Unknown desc = Exception was thrown by handler.
```

There don't appear to be any obvious error messages in the log output from EventStore related to this.  Other interactions with EventStore work fine e.g. calling `s.client.ReadStream` etc.  I'm running version `21.10.1` of EventStore.

Any advice would be appreciated 😄

**Comment by YoEight** [comment]
What connection string are you using?

**Comment by lukeparkzip** [comment]
Thanks for the fast response - my connection string looks like the below:

```
esdb://admin:changeit@some.redacted.hostname:2113?tls=false
```

**Comment by YoEight** [comment]
@lukeparkzip I forgot to ask, what version of the client are you using?

**Comment by lukeparkzip** [comment]
@YoEight - I'm on the latest, v1.0.2!

**Comment by lukeparkzip** [comment]
Hey @YoEight - any information you need further or any update on this one?  I can reliably produce this in multiple environments.

**Comment by YoEight** [comment]
Hey @lukeparkzip, could you try the master branch and see works better or have better reporting? I was not able to reproduce your issue but we did introduce some refinements and better error reporting over the last two weeks.

**Comment by lukeparkzip** [comment]
Hey @YoEight - thanks for the update - I adjusted my dependency to use commit `b85c3549a7c2` e.g.

```
require github.com/EventStore/EventStore-Client-Go v1.0.3-0.20220215140634-b85c3549a7c2
```

Which did slightly change the error message - I now receive the following:

```
maximum discovery attempt count reached: 10. Last Error: rpc error: code = Unavailable desc = connection closed
```

**Comment by YoEight** [comment]
Out of this message, all I can see is you can't connect to your server in the first place. Sending you persistent subscription creation requests to $all didn't even happen. Do you have more logs to share? Are you sure to use the right connection string to connect to your server?

**Comment by lukeparkzip** [comment]
Hey @YoEight - apologies, you're right - that one was caused by a different underlying problem - on that new version of the client, I now get simply `unsupported feature`.

**Comment by YoEight** [comment]
@lukeparkzip and now all you have to do is update your `master` version 😅 

A regression was addressed few days ago! https://github.com/EventStore/EventStore-Client-Go/pull/109

**Comment by lukeparkzip** [comment]
@YoEight Awesome this appears to have resolved the issue for me - thanks for your help, much appreciated 👍
